config/routes.rb
Rails.application.routes.draw do

  root to: 'loan_applications#index'

  match '/auth/:provider/callback', to: 'sessions#create', via: [ :get, :post ]
  match 'auth/failure', to: 'loan_applications#index', via: [ :get, :post ]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [ :get, :post ]
  match 'logout', to: 'sessions#destroy', as: 'logout', via: [ :get, :post ]

  resources :loan_applications, path: :applications

  resources :businesses, only: [ :update, :create, :show ] do
    resources :business_owners, only: [ :update, :create ]
  end

end

app/models/loan_application.rb
class LoanApplication < ActiveRecord::Base

  #
  # Relationships
  #
  belongs_to :business
	has_many :business_owners, through: :business

  #
  # Validations (very minimal for implementation)
  #
  validates :business, presence: true
  validates :requested_principle, presence: true,
    numericality: { only_integer: true, greater_than: 1000 }
  validates :requested_term_months, presence: true, inclusion: { in: LOAN_TERM_LENGTHS }
  validates :loan_mini_score, presence: true,
    numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 1 }
  validates_date :application_date, present: true, on_or_before: Date.today

  #
  # Returns array of integers representing the acceptable
  # term lengths (in months)
  #
	def self.terms
		LOAN_TERM_LENGTHS
	end
end

app/controllers/loan_applications_controller.rb
class LoanApplicationsController < ApplicationController

  include LoanApplicationsHelper

  around_filter :catch_not_found

  #
  # PUT /applications/:id
  #
  def create
    @application = LoanApplication.new(loan_application_params)
    @business = Business.new(business_params)

    #
    # For simplicity, let's just consider one associated BusinessOwner
    # record first. The model relationships to support multiple
    # BusinessOwners records are in place though.
    #
    @owner = BusinessOwner.new(owner_params)
    @owner.business = @business
    @owners = [ @owner ]
    @application.business = @business
    @application.application_date = Date.today

    # Set if Facebook session active
    omniauth_hash = session[:omniauth]

    respond_to do |format|

      #
      # Attempt to save Business and BusinessOwner records.
      #
      business_saved = @business.save
      owner_saved = @owner.save

      #
      # Build and save SocialMediaPresence if connected/authenticated with Facebook
      #
      if !omniauth_hash.nil?
        @social_media_presence = build_social_media_presence_for_business(omniauth_hash, @business)

        if @social_media_presence.save!
          @application.loan_mini_score = compute_credit_mini_score(@business)
          puts "SAVED successfully"
        else
          puts "SAVED UNSUCCESSFULLY"
        end
      end

      #
      # Finally, attempt to save LoanApplication record.
      #
      app_saved = @application.save

      if (app_saved && business_saved && owner_saved)

        flash[:success] = 'Loan application was successfully submitted.'
        format.html { redirect_to @application }
        format.json { render :show, status: :created, location: @application }
      else
        #
        # When attempting to save LoanApplication, Business, and BusinessOwner
        # records, treat them together as an "all-or-nothing" operation. Destroy
        # all records if any single one fails to save.
        #
        if app_saved
          @application.destroy
        end

        if business_saved
          @business.destroy
        end

        if owner_saved
          @owner.destroy
        end
        flash[:danger] = 'There was a problem submitting application'
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    #
    # NO-OP for simplicity
    #
  end

  #
  # GET /applications/new
  #
  def new
    @application = LoanApplication.new
    @business = @application.build_business
    @owner = @application.business_owners.build
    @owners = [ @owner ]
  end

  #
  # GET /applications/:id
  #
  def show
    @loan_application = LoanApplication.find(params[:id])
    @business = @loan_application.business
    @owners = @business.business_owners
  end

  #
  # GET /applications
  #
  def index
    @loan_applications = LoanApplication.all
  end


  private

  #
  # Redirect to root_url when RecordNotFound
  #
  def catch_not_found
    yield
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url, flash: { error: "Record not found." }
  end

  def loan_application_params
    params.require(:loan_application).permit(:requested_principle, :requested_term_months)
  end

  #
  # For minimal implelmentation, only accept some basic fields for 'Business' model
  #
  def business_params
    params.require(:loan_application).require(:business).permit(
      :legal_name, :founded_date, :num_employees, :business_url,
      :estimated_annual_revenue, :organization_type)
  end

  #
  # For minimal implelmentation, only accept some basic fields for 'BusinessOwner' model
  #
  def owner_params
    params.require(:loan_application).require(:business_owner).permit(
      :last_name, :first_name, :email, :phone_number, :percentage_ownership, :birthdate)
  end
end

app/helpers/loan_applications_helper.rb
module LoanApplicationsHelper


  #
  # Build a SocialMediaPresence object by invoking Facebook API
  # to fetch number of friends (num_connections)
  #
  def build_social_media_presence_for_business(omniauth_hash, business)

    oauth_access_token = omniauth_hash['credentials']['token']
    provider = omniauth_hash['provider']
    uid = omniauth_hash['uid']
    num_connections = get_facebook_friends(oauth_access_token).size

    # For simplicity, just consider provider as social_media_site field
    social_media_site = provider

    presence = SocialMediaPresence.new(
      provider: provider,
      uid: uid,
      num_connections: num_connections,
      social_media_site: social_media_site,
      business_id: business.id)
    presence
  end

  #
  # Base credit_mini_score on percentile of num_connections. If Business has no
  # associated social_media_presence, just report 0.
  #
  def compute_credit_mini_score(business)
    social_media_presences = business.social_media_presences

    credit_mini_score = 0
    unless social_media_presences.nil? || social_media_presences.size == 0
      credit_mini_score = (social_media_presences[0].calculate_num_connections_percentile / 10)
    end
    credit_mini_score
  end

  #
  # Using the specified oauth_access_token, invoke Facebook API using
  # Koala Gem. Return friends.
  #
  def get_facebook_friends(oauth_access_token)
    @graph = Koala::Facebook::API.new(oauth_access_token)
    friends = @graph.get_connections("me", "friends")
    friends
  end
end

app/views/loan_applications/_business_fields.html.erb
<!--
    PARTIAL CONTAINING FORM FIELDS FOR BUSINESS
    (rendered as part of LoanApplication form)
-->
<%= f.form_group do %>
  <%= f.fields_for @business do |bf| %>
    <%= bf.text_field :legal_name, hide_label: true, placeholder: 'Legal Name' %>
    <%= bf.text_field :employer_identification_number, hide_label: true, placeholder: 'EIN' %>
    <%= bf.select :organization_type, Business.org_types, prompt: 'Select type' %>
    <%= bf.text_field :address, hide_label: true, placeholder: 'Address' %>
    <%= bf.text_field :city, hide_label: true, placeholder: 'City' %>
    <%= bf.text_field :county, hide_label: true, placeholder: 'Country' %>
    <%= bf.text_field :state, hide_label: true, placeholder: 'State' %>
    <%= bf.text_field :zip, hide_label: true, placeholder: 'Zip' %>
    <%= bf.phone_field :phone_number, hide_label: true, placeholder: 'Phone' %>
    <%= bf.phone_field :fax_number, hide_label: true, placeholder: 'Fax' %>
    <%= bf.email_field :email, hide_label: true, placeholder: 'Email' %>
    <%= bf.date_select :founded_date %>
    <%= bf.text_field :estimated_annual_revenue, prepend: '$', append: '.00', hide_label: true, placeholder: 'Est. Annual Revenue' %>
    <%= bf.url_field :business_url, hide_label: true, placeholder: 'Business URL' %>
    <%= bf.number_field :num_employees, hide_label: true, placeholder: '# Employees' %>
  <% end %>

  <!-- DISPLAY FB ICON IF NOT ALREADY CONNECTED TO FB -->
  <% if connected_to_fb? %>
    <br/>
    <h4>Add facebook data:</h4>
    <%= link_to image_tag("facebook-icon.jpg", border: 0, width: 40, height: 40, alt: 'add facebook data'), '/auth/facebook' %>
  <% end %>
<% end %>

app/views/loan_applications/_form.html.erb
<%= bootstrap_form_for(@application, layout: :inline) do |f| %>

  <% if @application.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @application.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <br/>

  <!--
    LOAN APPLICATION FIELDS
  -->
  <h3>Loan Information</h3>
  <%= f.form_group do %>
    <%= f.text_field :requested_principle, prepend: '$', append: '.00', hide_label: true, placeholder: 'Requested Principle' %>
    <%= f.select :requested_term_months, LoanApplication.terms, prompt: 'Select Term', label: 'Term (months):' %>
  <% end %>
  <br/>

  <!--
    BUSINESS FIELDS
  -->
  <h3>Business Information</h3>
  <%= render partial: 'business_fields', locals: { f: f } %>
  <br/>
  <br/>

  <!--
    BUSINESS OWNER FIELDS
  -->
  <h3>Business Ownership</h3>
  <% for owner in @owners %>
    <%= render partial: 'owner_fields', locals: { f: f } %>
  <% end %>
  <button type="button" class="btn btn-success btn-sm">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add'l Owner
  </button>
  <br/>
  <br/>

  <%= f.form_group do %>
    <%= f.submit 'Submit Application', class: 'btn btn-primary' %>
    <%= link_to t('.cancel', default: t("helpers.links.cancel")),
              loan_applications_path, class: 'btn btn-default' %>
  <% end %>

<% end %>

app/views/loan_applications/_owner_fields.html.erb
<!--
    PARTIAL CONTAINING FORM FIELDS FOR BUSINESS_OWNER
    (rendered as part of LoanApplication form)
-->
<%= f.form_group do %>
  <%= f.fields_for @owner do |of| %>
    <%= of.text_field :first_name, hide_label: true, placeholder: 'First Name' %>
    <%= of.text_field :last_name, hide_label: true, placeholder: 'Last Name' %>
    <%= of.number_field :percentage_ownership, hide_label: true, placeholder: 'Ownership', append: '%' %>
    <%= of.date_select :birthdate, { order: [ :month, :day, :year ], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: Date.today.year - 18, end_year: Date.today.year - 100}, {required: true} %>
    <%= of.text_field :city, hide_label: true, placeholder: 'City' %>
    <%= of.text_field :state, hide_label: true, placeholder: 'State' %>
    <%= of.text_field :zip, hide_label: true, placeholder: "Zip" %>
    <%= of.phone_field :phone_number, hide_label: true, placeholder: 'Phone' %>
    <%= of.email_field :email, hide_label: true, placeholder: 'Email' %>
    <%= of.text_field :social_security_number, hide_label: true, placeholder: 'SSN' %>
    <%= of.text_field :drivers_license_number, hide_label: true, placeholder: 'Drivers License #' %>
    <%= of.text_field :estimated_liquid_assets, prepend: '$', append: '.00', hide_label: true, placeholder: 'Est. Liquid Assets' %>
    <%= of.number_field :estimated_outstanding_debt, prepend: '$', append: '.00', hide_label: true, placeholder: 'Est. Outst. Debt' %>
  <% end %>
<% end %>
<hr>

app/views/loan_applications/index.html.erb
<%- model_class = LoanApplication -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.pluralize.titleize %></h1>
</div>

<!--
  LOAN APPLICATIONS TABLE
-->
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:application_date) %></th>
      <th><%= model_class.human_attribute_name(:business_id) %></th>
      <th><%= model_class.human_attribute_name(:requested_principle) %></th>
      <th><%= model_class.human_attribute_name(:requested_term_months) %></th>
      <th><%= model_class.human_attribute_name(:loan_mini_score) %></th>
      <th><%=t '.actions', default: t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @loan_applications.each do |app| %>
      <tr>
        <td><%= app.application_date %></td>
        <td><%= app.business.nil? ? "" : link_to(app.business.legal_name, business_path(app.business)) %></td>
        <td><%= "$ #{app.requested_principle}" %></td>
        <td><%= app.requested_term_months %></td>
        <td><%= app.loan_mini_score %></td>
        <td>
          <%= link_to t('.destroy', default: t("helpers.links.destroy")),
                      loan_application_path(app),
                      method: :delete,
                      data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
                      class: 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', default: t("helpers.links.new")),
            new_loan_application_path,
            class: 'btn btn-primary' %>

app/views/loan_applications/new.html.erb
<%- model_class = LoanApplication -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<br/>
<%= render partial: 'form' %>

app/views/loan_applications/show.html.erb
<%- model_class = LoanApplication -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.titleize %></h1>
</div>

<!--
  LOAN APPLICATION INFORMATION
-->
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:business_id) %>:</strong></dt>
  <dd><%= link_to(@business.legal_name, business_path(@business)) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:application_date) %>:</strong></dt>
  <dd><%= @loan_application.application_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:requested_principle) %>:</strong></dt>
  <dd><%= @loan_application.requested_principle %></dd>
  <dt><strong><%= model_class.human_attribute_name(:requested_term_months) %>:</strong></dt>
  <dd><%= @loan_application.requested_term_months %></dd>
  <dt><strong><%= model_class.human_attribute_name(:loan_mini_score) %>:</strong></dt>
  <dd><%= @loan_application.loan_mini_score %></dd>
</dl>

<%= link_to t('.back', default: t("helpers.links.back")),
              loan_applications_path, :class => 'btn btn-default' %>
<%= link_to t('.destroy', default: t("helpers.links.destroy")),
              loan_application_path(@loan_application),
              :method => 'delete',
              :data => { :confirm => t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
              :class => 'btn btn-danger' %>